### ISSUE TITLE
Sharing URLs from browser does not work

### ISSUE THREAD

**Issue by cweiske** [matgoebl/Send2URL#2]
I'm trying to share an URL from the browser, but this does not work.

The HTTP request is never sent.

Sharing images does work, though.

---

`$ adb logcat` shows:

> I/ActivityManager(  704): START u0 {act=android.intent.action.SEND typ=text/plain flg=0x3080001 cmp=com.github.matgoebl.send2url/.SendActivity (has clip) (has extras)} from uid 10
> 038 on display 0

**Comment by matgoebl** [comment]
Closed by #5
